// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSLRrLZmxbIszj4C7q2dK1N2xr9oUfsaQ',
    appId: '1:1001918715286:web:24cf7fa686e77acd9f39b7',
    messagingSenderId: '1001918715286',
    projectId: 'goya-fleet',
    authDomain: 'goya-fleet.firebaseapp.com',
    storageBucket: 'goya-fleet.firebasestorage.app',
    measurementId: 'G-5BZXX5BQ44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDygAP1MchmQL4o3KE0FKhM4Lw0bU_lx_M',
    appId: '1:1001918715286:android:f26a3c9923645dda9f39b7',
    messagingSenderId: '1001918715286',
    projectId: 'goya-fleet',
    storageBucket: 'goya-fleet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjMDOrjPdmCtlIHdZBEyMNiBepWBUuSCg',
    appId: '1:1001918715286:ios:f96cba88065acf8b9f39b7',
    messagingSenderId: '1001918715286',
    projectId: 'goya-fleet',
    storageBucket: 'goya-fleet.firebasestorage.app',
    iosBundleId: 'com.example.fleet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjMDOrjPdmCtlIHdZBEyMNiBepWBUuSCg',
    appId: '1:1001918715286:ios:f96cba88065acf8b9f39b7',
    messagingSenderId: '1001918715286',
    projectId: 'goya-fleet',
    storageBucket: 'goya-fleet.firebasestorage.app',
    iosBundleId: 'com.example.fleet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSLRrLZmxbIszj4C7q2dK1N2xr9oUfsaQ',
    appId: '1:1001918715286:web:92740536bc90501d9f39b7',
    messagingSenderId: '1001918715286',
    projectId: 'goya-fleet',
    authDomain: 'goya-fleet.firebaseapp.com',
    storageBucket: 'goya-fleet.firebasestorage.app',
    measurementId: 'G-K0JB4J90PK',
  );
}
